apiVersion: v1
kind: Pod
metadata:
  name: nodefindanddev.example.com
  labels:
    app: my-site
spec:
  containers:
    - name: findanddev
      image: johshe/findanddev
      ports:
        - name: nodejs-port
          containerPort: 3000
